[package]
name = "bevy-pixel-buffers"
version = "0.1.0"
edition = "2021"
exclude = ["assets/"]

[dependencies]
bevy = "0.12"
buffer-graphics-lib = "0.15.1"
graphics-shapes = "0.4.0"
image = "0.24"
serde = "1"

[[example]]
name = "main_menu"
path = "examples/main_menu.rs"
